{
    'name': 'BI VAS AMC',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'version': '18.0.1.3.1',
    'category': 'sale',
    'summary': ''' BI VAS AMC ''',
    'description': '''BI VAS AMC''',
    'depends': ['stock','sale','project','sale_subscription', 'account', 'sale_management'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/data.xml',
        'views/sale_order.xml',
        'views/detailed_spec.xml',
        'views/project.xml',
        'views/sale_subscription_plan.xml',
        'views/product_template.xml',
        'views/sale_order_grp.xml',
        'views/project_sever_action.xml',
        'views/update_analytic_account.xml',
    ],
    'installable': True,
    'application': False,
    'images': [],
    'license': 'OPL-1',
}
