{
    'name': 'BI Purchase Requisition',
    'summary': ''' BI Purchase Requisition ''',
    'description': ''' BI Purchase Requisition ''',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'category': 'purchase',
    'depends': ['web','hr','purchase','mail','account','sale','bi_vas_amc','purchase_requisition','bi_purchase_order_report'],
    'version': '18.0.1.0.4',
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/data.xml',
        'data/activity.xml',
        # 'data/mail_template_rfq.xml',
        'views/purchase_request.xml',
        'views/purchase_order.xml',
        'views/purchase_requisition_new.xml',
        'views/bi_purchase_order.xml',
        'views/bi_purchase_quotation.xml',
        'wizards/purchase_request_wizard.xml',
        'wizards/purchase_rquation_wizard.xml',
        'views/purchase_request_buk_approval.xml',
        'wizards/reject_wizard.xml',
        'wizards/quotation_wizard.xml'
    ],
    'images': [],
    'license': 'OPL-1',
    'installable': True,
    'application': False,
}
