{
    'name': 'BI CRM',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'version': '18.0.2.1.7',
    'category': 'CRM',
    'summary': ''' BI CRM ''',
    'description': '''BI CRM''',
    'depends': ['crm','bi_survey_form','sale_crm','sale',],
    'data': [
        'security/ir.model.access.csv',
        'data/activity.xml',
        'views/crm_lead.xml',
        'views/item_master.xml',
        'views/hr_job.xml',        
    ],
    'images': [],
    'installable': True,
    'application': False,
    'images': [],
    'license': 'OPL-1',
}
