{
    'name': 'BI AMC PROPOSAL',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'version': '18.0.1.7.9',
    'category': 'SALE',
    'summary': ''' BI AMC PROPOSAL ''',
    'description': '''BI AMC PROPOSAL''',
    'depends':['base','sale','sale_stock','report_qweb_element_page_visibility','bi_vas_amc','sale_management','bi_sale','web'],
    'data': [
        'security/ir.model.access.csv',
        'views/sale_order_views.xml',
        'report/amc_proposal_report.xml',
        'views/corporate_menu.xml',
        'views/vas_menu.xml',
        'views/completion_period.xml',
        'views/res_company_views.xml',
        'views/basic_layout.xml',
        'report/paper_format.xml',
        'report/vas_template1_header.xml',
        'report/report_header1.xml',
        'report/vas_report_action.xml',
        'report/amc_proposal_template.xml',
        'report/amc_proposal_template_corporate.xml',
        'report/vas_proposal_template.xml',
        'report/vas_proposal_template1.xml',
        'report/water_feature_template.xml',
    ],
    'images': ['/bi_amc_proposal/static/src/img/healthwave_logo.png',
               '/bi_amc_proposal/static/src/img/kehlan_pools_logo.png',
               '/bi_amc_proposal/static/src/img/poolcleaning.png',
               '/bi_amc_proposal/static/src/img/purepool.png',
               '/bi_amc_proposal/static/src/img/kehlan_andheathwave_logo.png',
            #    '/bi_amc_proposal/static/src/img/kehlanpools_fountains_logo.png',
                '/bi_amc_proposal/static/src/img/test1.png',
                '/bi_amc_proposal/static/src/img/about.png',
               '/bi_amc_proposal/static/src/img/one.png',
               '/bi_amc_proposal/static/src/img/two.png',
               '/bi_amc_proposal/static/src/img/three.png',
               '/bi_amc_proposal/static/src/img/four.png',
               '/bi_amc_proposal/static/src/img/five.png',
               '/bi_amc_proposal/static/src/img/six.png',
               '/bi_amc_proposal/static/src/img/eight.png',
               
    ],
    'installable': True,
    'application': False,
    'images': [],
    'license': 'OPL-1',
}
