{
    'name': 'bi fleet',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'version': '18.0.1.0.3',
    'category': 'fleet',
    'summary': ''' bi fleet ''',
    'description': '''bi fleet''',
    'depends': ['fleet','base_geolocalize','hr','documents_fleet'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/vehicle_route.xml',
        'views/fleet_vehicle.xml',
        'views/damage_image.xml',
        'views/fleet_vehicle_odometer.xml',
        'views/fleet_vehicle_document.xml',
        'views/hr_job.xml',
    ],
    'assets': {
        'web.assets_backend': [
            "https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" ,
            'https://unpkg.com/leaflet@1.7.1/dist/leaflet.js',
            'bi_fleet/static/src/css/goelocation_map.css',
            'bi_fleet/static/src/js/geolocation_map.js',
            'bi_fleet/static/src/xml/geolocation_map_templates.xml',
        ],
    },
    'images': [],
    'installable': True,
    'application': False,
    'images': [],
    'license': 'OPL-1',
}
