{
    'name': 'BI Employee Document Expiry Warning',
    'summary': ''' BI Employee Document Expiry warning ''',
    'description': '''BI Employee Document Expiry''',
    'author': 'Bassam Infotech LLP',
    'company': 'Bassam Infotech LLP',
    'maintainer': 'Bassam Infotech LLP',
    'website': 'https://bassaminfotech.com',
    'category': 'HR',
    'depends': ["base",'hr','documents_hr'],
    'version': '18.0.1.0.4',
    'data': [
        'security/ir.model.access.csv',
        'data/employee_checklist_data.xml',
        'data/ir_cron_data.xml',
        'views/employee_checklist_views.xml',
        'views/hr_employee_document_views.xml',
        'views/hr_employee_views.xml',
        'views/activity.xml',
    ],
    'images': ["bi_employee_document_expiry_warning/static/description/icon.png"],
    'license': 'OPL-1',
    'installable': True,
    'application': False,
}
